image: joyzoursky/python-chromedriver:3.9-selenium

stages:
  - test

run_tests:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest --alluredir=allure-results
  artifacts:
    when: always
    paths:
      - allure-results
    expire_in: 1 week