[pytest]
log_cli = true
log_cli_level = INFO
pythonpath = .

testpaths =
    tests
    ui/selenium/apps/reqres/tests
    ui/selenium/apps/samokat/tests
    ui/selenium/apps/the_internet/tests
    ui/selenium/apps/automation_exercise/tests

markers =
    api: api tests
    ui: ui tests

addopts =
    -v
    --strict-markers
